Repository misha1235000/SpikeServer, pull requests merged in 2018-09, with the labels that each got.

#54 fix: Added cors middleware, which has fixed the headers problem. Clos…
  package-lock.json
  package.json
  src/app.ts
Labels: bug, invalid

#57 fix: Fix the password validator location, Refactor some of the code.
  src/auth/auth.controller.ts
  src/team/team.validator.ts
  src/utils/error.handler.ts
Labels: invalid, refactor

#59 fix: Fix password not valid error.
  src/team/team.model.ts
Labels: bug, invalid

#62 Refactor team password hashing
  src/auth/auth.controller.ts
  src/team/team.model.ts
Labels: enhancement, refactor

#63 chore: Update README.md. Closes #50
  README.md
Labels: readme

#64 chore: Add contribute.md
  CONTRIBUTING.md
Labels: contribute

#65 chore: Add license.
  LICENSE
Labels: LICENSE

#66 chore: Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: CODE_OF_CONDUCT

#67 chore: Add Issue Template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: issue_template

#68 chore: Add PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: pull_request_template

#69 chore: Change License and Contributing description
  README.md
Labels: README

#70 chore: Rename License to License.md
  LICENSE.md
Labels: LICENSE

#71 Fix authorization server intergration error
  src/app.ts
  src/client/client.controller.ts
  src/client/client.repository.ts
  src/client/client.router.ts
  src/config.ts
  src/oauth2/oauth2.controller.ts
  src/oauth2/oauth2.parser.ts
  src/utils/error.handler.ts
Labels: bug, invalid

#72 fix: Fix mongo model teamid to not be unique.
  src/client/client.model.ts
Labels: enhancement, mongo

#73 Client model
  src/client/client.interface.ts
  src/client/client.model.ts
  src/client/client.validator.ts
  src/oauth2/oauth2.parser.ts
Labels: bug, invalid, mongo

#75 fix: Parse to ClientInformation add. Remove unused mongo data.
  src/client/client.model.ts
  src/oauth2/oauth2.parser.ts
Labels: enhancement, mongo
