Repository misha1235000/SpikeServer, pull requests merged in 2018-08, with the labels that each got.

#10 Client
  src/client/client.controller.ts
  src/client/client.interface.ts
  src/client/client.model.ts
  src/client/client.repository.ts
  src/client/client.router.ts
  src/client/client.validator.ts
  src/utils/warpper.ts
Labels: feature

#12 User
  src/user/user.controller.ts
  src/user/user.model.ts
  src/user/user.repository.ts
  src/user/user.validator.ts
Labels: enhancement

#17 refactor: Deleted unnecessary auth files. Closes #15
  src/auth/auth.interface.ts
  src/auth/auth.model.ts
  src/auth/auth.repository.ts
  src/auth/auth.token.ts
  src/auth/auth.validator.ts
Labels: remove

#18 refactor: Added documentation to all files. Closes #16
  src/app.ts
  src/auth/auth.controller.ts
  src/auth/auth.router.ts
  src/client/client.controller.ts
  src/client/client.interface.ts
  src/client/client.model.ts
  src/client/client.repository.ts
  src/client/client.router.ts
  src/client/client.validator.ts
  src/config.ts
  src/oauth2/oauth2.controller.ts
  src/server.ts
  src/user/user.controller.ts
  src/user/user.interface.ts
  src/user/user.model.ts
  src/user/user.repository.ts
  src/user/user.router.ts
  src/user/user.validator.ts
  src/utils/warpper.ts
Labels: design

#20 fix: Added client validators. Closes #9
  src/auth/auth.controller.ts
  src/client/client.controller.ts
  src/client/client.model.ts
  src/client/client.validator.ts
  src/user/user.controller.ts
  src/user/user.repository.ts
  src/user/user.validator.ts
Labels: enhancement

#26 refactor: Changed user to team. Closes #21
  src/app.ts
  src/auth/auth.controller.ts
  src/client/client.model.ts
  src/client/client.validator.ts
  src/team/team.controller.ts
  src/team/team.interface.ts
  src/team/team.model.ts
  src/team/team.repository.ts
  src/team/team.router.ts
  src/team/team.validator.ts
  src/user/user.repository.ts
  src/user/user.router.ts
  src/user/user.validator.ts
Labels: refactor

#30 refactor: Added team error handler. Closes #19
  src/team/team.controller.ts
  src/team/team.error.ts
  src/team/team.repository.ts
  src/team/team.validator.ts
Labels: enhancement

#31 refactor: Add error handler for Auth controller. Closes #24
  src/auth/auth.controller.ts
  src/auth/auth.error.ts
Labels: enhancement

#32 Client error handler
  src/client/client.controller.ts
  src/client/client.error.ts
  src/client/client.repository.ts
  src/client/client.validator.ts
  src/team/team.controller.ts
Labels: enhancement

#33 Generic error handler
  src/auth/auth.controller.ts
  src/auth/auth.error.ts
  src/client/client.controller.ts
  src/client/client.error.ts
  src/client/client.repository.ts
  src/client/client.validator.ts
  src/team/team.controller.ts
  src/team/team.error.ts
  src/utils/error.ts
Labels: enhancement

#34 fix: Change all the functions to pass by an authorize middleware. Clo…
  src/app.ts
  src/auth/auth.controller.ts
  src/team/team.router.ts
Labels: enhancement

#37 Client routes
  src/app.ts
  src/auth/auth.router.ts
Labels: enhancement

#38 fix: Fix Import Error
  src/team/team.repository.ts
Labels: bug

#39 fix: Fix MongoError import.
  src/client/client.controller.ts
Labels: bug, invalid

#41 Oauth logic and error handler
  package-lock.json
  package.json
  src/app.ts
  src/auth/auth.error.ts
  src/config.ts
  src/oauth2/oauth2.controller.ts
  src/oauth2/oauth2.error.ts
  src/oauth2/oauth2.parser.ts
  src/utils/error.ts
Labels: feature

#46 fix: Fix error handler function, to handle all kind of errors. Closes…
  src/utils/error.handler.ts
Labels: bug
